### ISSUE TITLE
Add SHIELD in tools section

### ISSUE THREAD

**Issue by khuzama98** [heypran/zk-block#23]
Kindly add SHIELD as a development framework for ZK-based languages in the tools section.
You can find more details on the notion,
notion: https://xord.notion.site/SHIELD-5306223ca4f745d19f54b9a5f4004cd6

**Comment by heypran** [comment]
can you open a PR here - https://github.com/heypran/zk-tools/blob/main/src/data/tools.ts

**Comment by khuzama98** [comment]
Sure @heypran.

**Comment by heypran** [comment]
Addressed here https://github.com/heypran/zk-tools/pull/2
